name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install requests
        pip install kaggle
        pip install SQLAlchemy

    - name: Kaggle Credentials
      run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.USER_KAGGLE }}\",\"key\":\"${{ secrets.PASSWORD_KAGGLE }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
    - name: Allow pipeline execute permission
      run: chmod +x pipeline.sh
      
    - name: Execute pipeline
      run: |
          cd project
          ./pipeline.py
    
    - name: Execute Tests
      run: chmod +x Tests.sh

    - name: Execute Test Script
      run: ./Tests.sh
          